public typealias DescriptorUpdateTemplateKHR = DescriptorUpdateTemplate
public typealias SamplerYcbcrConversionKHR = SamplerYcbcrConversion
public typealias AccelerationStructureNV = AccelerationStructureKHR
